[[redirects]]
from = "https://awesome-bassi-04323e.netlify.com/*"
to = "/:splat"
status = 301
force = true

[[redirects]]
from = "http://awesome-bassi-04323e.netlify.com/*"
to = "/:splat"
status = 301
force = true
